name = "gps-tracker" # Hoặc tên dự án của bạn
main = "worker.js"   # Đường dẫn tới file code của bạn
compatibility_date = "2026-01-01"

[[kv_namespaces]]
binding = "TRACKER_KV"
id = "f5e67ea5348240b0b1c51d80cd120269"